// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MarkdownDeepTest {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MarkdownDeepTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LegacyTestSource {
            get {
                return ResourceManager.GetString("LegacyTestSource", resourceCulture);
            }
        }
        
        internal static string LegacyTestSourceResult {
            get {
                return ResourceManager.GetString("LegacyTestSourceResult", resourceCulture);
            }
        }
        
        internal static string LinkTestSource {
            get {
                return ResourceManager.GetString("LinkTestSource", resourceCulture);
            }
        }
        
        internal static string ImageTestSource {
            get {
                return ResourceManager.GetString("ImageTestSource", resourceCulture);
            }
        }
        
        internal static string AudioTestSource {
            get {
                return ResourceManager.GetString("AudioTestSource", resourceCulture);
            }
        }
        
        internal static string VideoTestSource {
            get {
                return ResourceManager.GetString("VideoTestSource", resourceCulture);
            }
        }
    }
}
