
// This file has been generated by the GUI designer. Do not modify.
namespace MDGui.Gtk3
{
	public partial class Widget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MDGui.Gtk3.Widget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MDGui.Gtk3.Widget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
